apiVersion: apps/v1
kind: Deployment
metadata:
    name: story-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: story
    template:
        metadata:
            labels:
                app: story
        spec:
            containers:
                - name: story
                  image: codyle212/data-demo:latest
                  imagePullPolicy: Always
                  env:
                      - name: STORY_FLODER
                        # value: 'story'
                        valueFrom:
                            configMapKeyRef:
                                name: data-store-env
                                key: folder
                  volumeMounts:
                      - mountPath: /app/story
                        name: story-volume
            volumes:
                - name: story-volume
                  persistentVolumeClaim:
                      claimName: host-pvc
