apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: host-vpc
spec:
    volumeName: host-pv
    accessModes:
        - ReadWriteOnce
    storageClassName: standard
    resources:
        requests:
            storage: 1Gi
